# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty
# relative_permalinks: true

# Setup
title:            Vlad Ghita
tagline:          'Computer Enthusiast'
description:      'Software <a href="http://www.p1.ro" target="_blank">Developer.</a> Computer Enthusiast.'
url:              http://www.vladghita.com
baseurl:          /

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/poole/hyde
